### ISSUE TITLE
Allowing single quotes & double quotes breaks URL

### ISSUE THREAD

**Issue by tsega** [yasaricli/meteor-slugify#1]
I'm using this package to generate my slugs but since the library [does not purge](https://github.com/yasaricli/meteor-slugify/blob/master/slugify.js#L80) single quotes `'` or double quotes `"` my URL breaks if the string I want to convert contains these characters.

Is this intentional? If not, can it be fixed?

**Comment by markdowney** [comment]
+1

**Comment by yasaricli** [comment]
thank you @tsega @markdowney ready @0.0.7
